# Generated by Django 3.2.4 on 2021-06-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('face', models.ImageField(upload_to='photo')),
                ('narration', models.TextField()),
            ],
        ),
    ]
